//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 05:35:17 PM CET 
//


package monpkg;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numero",
    "semaines",
    "mois"
})
@XmlRootElement(name = "annee")
public class Annee {

    @XmlAttribute(name = "xmlns")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String xmlns;
    @XmlElement(required = true)
    protected Numero numero;
    @XmlElement(required = true)
    protected Semaines semaines;
    @XmlElement(required = true)
    protected List<Mois> mois;

    /**
     * Gets the value of the xmlns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlns() {
        if (xmlns == null) {
            return "";
        } else {
            return xmlns;
        }
    }

    /**
     * Sets the value of the xmlns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlns(String value) {
        this.xmlns = value;
    }

    /**
     * Gets the value of the numero property.
     * 
     * @return
     *     possible object is
     *     {@link Numero }
     *     
     */
    public Numero getNumero() {
        return numero;
    }

    /**
     * Sets the value of the numero property.
     * 
     * @param value
     *     allowed object is
     *     {@link Numero }
     *     
     */
    public void setNumero(Numero value) {
        this.numero = value;
    }

    /**
     * Gets the value of the semaines property.
     * 
     * @return
     *     possible object is
     *     {@link Semaines }
     *     
     */
    public Semaines getSemaines() {
        return semaines;
    }

    /**
     * Sets the value of the semaines property.
     * 
     * @param value
     *     allowed object is
     *     {@link Semaines }
     *     
     */
    public void setSemaines(Semaines value) {
        this.semaines = value;
    }

    /**
     * Gets the value of the mois property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mois property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMois().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mois }
     * 
     * 
     */
    public List<Mois> getMois() {
        if (mois == null) {
            mois = new ArrayList<Mois>();
        }
        return this.mois;
    }

}
